=== SergeiNevostruev/backend_marathon_Lad/bson/src/schema/test_bson_data_validator.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "orders": {
      "type": "array",
      "items": [{
        "type": "object",
        "properties": {
          "readyForDelivery": {
            "type": "boolean"
          },
          "finalDocument": {
            "type": "boolean"
          },
          "receiverStreet": {
            "type": "string"
          },
          "receiverLocation": {
            "type": "string"
          },
          "receiverHouse": {
            "type": "string"
          },
          "receiverBuilding": {
            "type": "string"
          },
          "receiverCorpus": {
            "type": "string"
          },
          "receiverFlat": {
            "type": "string"
          },
          "fragile": {
            "type": "boolean"
          },
          "mail小ategory": {
            "type": "string"
          },
          "clientName": {
            "type": "string"
          },
          "orderId": {
            "type": "string"
          },
          "receiverCityName": {
            "type": "string"
          },
          "region": {
            "type": "string"
          },
          "index": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "deliveryId": {
            "type": "integer"
          },
          "barcode": {
            "type": "string"
          },
          "weight": {
            "type": "number"
          },
          "products": {
            "type": "array",
            "items": [{
              "type": "object",
              "properties": {
                "readyForDelivery": {
                  "type": "boolean"
                },
                "finalDocument": {
                  "type": "boolean"
                },
                "receiverStreet": {
                  "type": "string"
                },
                "receiverLocation": {
                  "type": "string"
                },
                "receiverHouse": {
                  "type": "string"
                },
                "receiverBuilding": {
                  "type": "string"
                },
                "receiverCorpus": {
                  "type": "string"
                },
                "receiverFlat": {
                  "type": "string"
                },
                "fragile": {
                  "type": "boolean"
                },
                "mail小ategory": {
                  "type": "string"
                },
                "clientName": {
                  "type": "string"
                },
                "orderId": {
                  "type": "string"
                },
                "receiverCityName": {
                  "type": "string"
                },
                "region": {
                  "type": "string"
                },
                "index": {
                  "type": "string"
                },
                "status": {
                  "type": "string"
                },
                "phone": {
                  "type": "string"
                },
                "deliveryId": {
                  "type": "integer"
                },
                "barcode": {
                  "type": "string"
                },
                "weight": {
                  "type": "integer"
                },
                "products": {
                  "type": "array",
                  "items": [{
                    "type": "object",
                    "properties": {
                      "productArt": {
                        "type": "string"
                      },
                      "productName": {
                        "type": "string"
                      },
                      "productUuid": {
                        "type": "string"
                      },
                      "quantity": {
                        "type": "integer"
                      },
                      "sku": {
                        "type": "string"
                      },
                      "status": {
                        "type": "string"
                      },
                      "weight": {
                        "type": "number"
                      },
                      "gtin": {
                        "type": "string"
                      },
                      "serialNumberMark": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "productArt",
                      "productName",
                      "productUuid",
                      "quantity",
                      "sku",
                      "status",
                      "weight",
                      "gtin",
                      "serialNumberMark"
                    ]
                  }]
                },
                "transportPallet": {
                  "type": "string"
                },
                "postOffice": {
                  "type": "string"
                },
                "orderCreatedAt": {
                  "type": "string",
                  "format": "date-time"
                },
                "mailType": {
                  "type": "string"
                },
                "deliveryStatus": {
                  "type": "array",
                  "items": [{
                    "type": "object",
                    "properties": {
                      "deliveryStatusDate": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "deliveryCode": {
                        "type": "integer"
                      },
                      "deliveryAttr": {
                        "type": "integer"
                      },
                      "deliveryStatus": {
                        "type": "string"
                      },
                      "_id": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "deliveryStatusDate",
                      "deliveryCode",
                      "deliveryAttr",
                      "deliveryStatus",
                      "_id"
                    ]
                  }]
                }
              },
              "required": [
                "readyForDelivery",
                "finalDocument",
                "receiverStreet",
                "receiverLocation",
                "receiverHouse",
                "receiverBuilding",
                "receiverCorpus",
                "receiverFlat",
                "fragile",
                "mail小ategory",
                "clientName",
                "orderId",
                "receiverCityName",
                "region",
                "index",
                "status",
                "phone",
                "deliveryId",
                "barcode",
                "weight",
                "products",
                "transportPallet",
                "postOffice",
                "orderCreatedAt",
                "mailType",
                "deliveryStatus"
              ]
            }]
          }
        },
        "required": [
          "readyForDelivery",
          "finalDocument",
          "receiverStreet",
          "receiverLocation",
          "receiverHouse",
          "receiverBuilding",
          "receiverCorpus",
          "receiverFlat",
          "fragile",
          "mail小ategory",
          "clientName",
          "orderId",
          "receiverCityName",
          "region",
          "index",
          "status",
          "phone",
          "deliveryId",
          "barcode",
          "weight",
          "products"
        ]
      }]
    },
    "storeId": {
      "type": "string"
    },
    "postOffice": {
      "type": "string"
    },
    "createdAt": {
      "type": "string",
      "format": "date-time"
    },
    "updatedAt": {
      "type": "string",
      "format": "date-time"
    }
  },
  "required": [
    "id",
    "status",
    "name",
    "orders",
    "storeId",
    "postOffice",
    "createdAt",
    "updatedAt"
  ]
}

=== SergeiNevostruev/backend_marathon_Lad/bson/src/testJsonFiles/test_bson_data_validator.json
{
    "id": "ID 1",
    "status": "Status 1",
    "name": "This is a name",
    "orders": [{
          "readyForDelivery": true,
          "finalDocument": true,
          "receiverStreet": "string",
          "receiverLocation": "string",
          "receiverHouse": "string",
          "receiverBuilding": "string",
          "receiverCorpus": "string",
          "receiverFlat": "string",
          "fragile": true,
          "mailСategory": true,
          "clientName": "string",
          "orderId": "string",
          "receiverCityName": "string",
          "region": "string",
          "index": "string",
          "status": "string",
          "phone": "string",
          "deliveryId": 5,
          "barcode": "string",
          "weight": 5,
          "products": 
            [ {
                "readyForDelivery": true,
                "finalDocument": true,
                "receiverStreet": "string",
                "receiverLocation": "string",
                "receiverHouse": "string",
                "receiverBuilding": "string",
                "receiverCorpus": "string",
                "receiverFlat": "string",
                "fragile": "string",
                "mailСategory": "string",
                "clientName": "string",
                "orderId": "string",
                "receiverCityName": "string",
                "region": "string",
                "index": "string",
                "status": "string",
                "phone": "string",
                "deliveryId": 5,
                "barcode": "string",
                "weight": 8,
                "products":  [ {
                      "productArt": "string",
                      "productName": "string",
                      "productUuid": "string",
                      "quantity": 7,
                      "sku": "string",
                      "status": "string",
                      "weight": 9,
                      "gtin": "string",
                      "serialNumberMark": "string"
                    }],
                "transportPallet": "string",
                "postOffice": "string",
                "orderCreatedAt": "2018-11-13T20:20:39+00:00",
                "mailType": "string",
                "deliveryStatus": [ {
                      "deliveryStatusDate": "2018-11-13T20:20:39+00:00",
                      "deliveryCode": 8,
                      "deliveryAttr": 8,
                      "deliveryStatus": "string",
                      "_id": "string"
                    }]
                
              }]          
        }],
    "storeId": "string",
    "postOffice": "string",
    "createdAt": "2018-11-13T20:20:39+00:00",
    "updatedAt": "2018-11-13T20:20:39+00:00"
  }
